# Source: pulsar/templates/toolset-service-account.yaml
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pulsar-mini-toolset"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: toolset
---

# Source: pulsar/templates/toolset-service.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: "pulsar-mini-toolset"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: toolset
spec:
  clusterIP: None
  selector:
    app: pulsar
    release: pulsar-mini
    component: toolset
---

