## Source: pulsar/templates/bookkeeper-cluster-initialize.yaml
#
apiVersion: batch/v1
kind: Job
metadata:
  name: "pulsar-mini-bookie-init"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: "bookie-init"
spec:
# This feature was previously behind a feature gate for several Kubernetes versions and will default to true in 1.23 and beyond
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  template:
    spec:
      
      serviceAccountName: "pulsar-mini-bookie"
#      initContainers:
#      - name: wait-zookeeper-ready
#        image: "apachepulsar/pulsar-all:4.0.2"
#        imagePullPolicy: "IfNotPresent"
#        resources: 
#          requests:
#            cpu: 0.1
#            memory: 256Mi
#        command: ["timeout", "600", "sh", "-c"]
#            until nslookup pulsar-mini-zookeeper-0.pulsar-mini-zookeeper.pulsar; do
#        args:
#          - >-
#
#            until nslookup pulsar-mini-zookeeper-0.pulsar-mini-zookeeper.pulsar; do
#              sleep 3;
#            echo "Zookeeper ready";
#            done;
      containers:
      - name: "pulsar-mini-bookie-init"
        image: "apachepulsar/pulsar-all:4.0.2"
        imagePullPolicy: "IfNotPresent"
        command: ["timeout", "60", "sh", "-c"]
        args:
          - >
            bin/apply-config-from-env.py conf/bookkeeper.conf;
            /pulsar/keytool/keytool.sh toolset ${HOSTNAME}.pulsar-mini-toolset.pulsar.svc.cluster.local true;

            echo "Keytool completed"            
            export BOOKIE_MEM="-Xmx128M";
#            if timeout 15 bin/bookkeeper shell whatisinstanceid; then
#                echo "bookkeeper cluster already initialized";
#            else
#                bin/pulsar zookeeper-shell -server pulsar-mini-zookeeper create / && echo 'created for pulsar cluster "pulsar-mini"' &&
#                bin/bookkeeper shell initnewcluster;
#            fi
        envFrom:
        - configMapRef:
            name: "pulsar-mini-bookie"
        volumeMounts:
        - name: toolset-certs
          mountPath: "/pulsar/certs/toolset"
          readOnly: true
        - name: ca
          mountPath: "/pulsar/certs/ca"
          readOnly: true
        - name: keytool
          mountPath: "/pulsar/keytool/keytool.sh"
          subPath: keytool.sh
        
      volumes:
      - name: toolset-certs
        secret:
          secretName: "pulsar-mini-tls-toolset"
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
      - name: ca
        secret:
          secretName: "pulsar-mini-ca-tls"
          items:
          - key: ca.crt
            path: ca.crt
      - name: keytool
        configMap:
          name: "pulsar-mini-keytool-configmap"
          defaultMode: 0755
      restartPolicy: OnFailure
---

