# Source: pulsar/templates/proxy-statefulset.yaml
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "pulsar-mini-proxy"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: proxy
spec:
  serviceName: "pulsar-mini-proxy"
  replicas: 3
  selector:
    matchLabels:
      app: pulsar
      release: pulsar-mini
      component: proxy
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: pulsar
        release: pulsar-mini
        cluster: pulsar-mini
        component: proxy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
#      affinity:
      terminationGracePeriodSeconds: 30
      serviceAccountName: "pulsar-mini-proxy"
#      initContainers:
      # This init container will wait for zookeeper to be ready before
      # deploying the bookies
#      - name: wait-zookeeper-ready
#        image: "apachepulsar/pulsar-all:4.0.2"
#        imagePullPolicy: "IfNotPresent"
#        resources: 
#          requests:
#            cpu: 0.1
#            memory: 256Mi
#        command: ["timeout", "600", "sh", "-c"]
#        args:
#          - >-
#            export PULSAR_MEM="-Xmx128M";
#            until timeout 15 bin/pulsar zookeeper-shell -server pulsar-mini-zookeeper get /admin/clusters/pulsar-mini; do
#              sleep 3;
#            done;
      # This init container will wait for at least one broker to be ready before
      # deploying the proxy
#      - name: wait-broker-ready
#        image: "apachepulsar/pulsar-all:4.0.2"
#        imagePullPolicy: "IfNotPresent"
#        resources: 
#          requests:
#            cpu: 0.1
#            memory: 256Mi
#        command: ["timeout", "120", "sh", "-c"]
#        args:
#          - >-
#            set -e;
#            brokerServiceNumber="$(nslookup -timeout=10 pulsar-mini-broker | grep Name | wc -l)";
#            until [ ${brokerServiceNumber} -ge 1 ]; do
#              echo "pulsar cluster pulsar-mini isn't initialized yet ... check in 10 seconds ...";
#              sleep 10;
#              brokerServiceNumber="$(nslookup -timeout=10 pulsar-mini-broker | grep Name | wc -l)";
#            done;
      containers:
      - name: "pulsar-mini-proxy"
        image: "apachepulsar/pulsar-all:4.0.2"
        imagePullPolicy: "IfNotPresent"
#        livenessProbe:
#          httpGet:
#            path: /status.html
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          timeoutSeconds: 5
#          failureThreshold: 10
#        readinessProbe:
#          httpGet:
#            path: /status.html
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          timeoutSeconds: 5
#          failureThreshold: 10
#        resources:
#          requests:
#            cpu: 0.2
#            memory: 128Mi
        command: ["sh", "-c"]
        args:
        - >
          bin/apply-config-from-env.py conf/proxy.conf &&
          echo "OK" > "${statusFilePath:-status}" &&
          OPTS="${OPTS} -Dlog4j2.formatMsgNoLookups=true" exec bin/pulsar proxy
        ports:
        # prometheus needs to access /metrics endpoint
        - name: sts-http
          containerPort: 8080
        - name: "sts-pulsar"
          containerPort: 6650
        - name: sts-https
          containerPort: 443
        - name: "sts-pulsar-tls"
          containerPort: 6651
        envFrom:
        - configMapRef:
            name: "pulsar-mini-proxy"
---

