# Source: pulsar/templates/proxy-service-account.yaml
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "pulsar-mini-proxy"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: proxy
  annotations:
---

# Source: pulsar/templates/proxy-service.yaml
#
apiVersion: v1
kind: Service
metadata:
  name: "pulsar-mini-proxy"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: proxy
  annotations:
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: sts-http
    - name: https
      port: 443
      protocol: TCP
      targetPort: sts-https
    - name: "pulsar"
      port: 6650
      protocol: TCP
      targetPort: "sts-pulsar"
    - name: "pulsar-tls"
      port: 6651
      protocol: TCP
      targetPort: "sts-pulsar-ssl"
  selector:
    app: pulsar
    release: pulsar-mini
    component: proxy
---

