# Source: pulsar/templates/pulsar-cluster-initialize.yaml
#
apiVersion: batch/v1
kind: Job
metadata:
  name: pulsar-mini-pulsar-init
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: pulsar-init
spec:
# This feature was previously behind a feature gate for several Kubernetes versions and will default to true in 1.23 and beyond
# https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
  template:
    spec:
      
      initContainers:
      - name: wait-zk-metastore-ready
        image: "apachepulsar/pulsar-all:4.0.2"
        imagePullPolicy: "IfNotPresent"
        resources: 
          requests:
            cpu: 0.1
            memory: 256Mi
        command: ["timeout", "600", "sh", "-c"]
        args:
          - >-
            until nslookup pulsar-mini-zookeeper-0.pulsar-mini-zookeeper.pulsar; do
              sleep 3;
            done;
      # This initContainer will wait for bookkeeper initnewcluster to complete
      # before initializing pulsar metadata
      - name: pulsar-bookkeeper-verify-clusterid
        image: apachepulsar/pulsar-all:4.0.2
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            cpu: 0.1
            memory: 256Mi
        command: ["timeout", "120", "sh", "-c"]
        args:
        - >-
          bin/apply-config-from-env.py conf/bookkeeper.conf;
          echo Default BOOKIE_MEM settings are set very high, which can cause the init container to fail.;
          echo Setting the memory to a lower value to avoid OOM as operations below are not memory intensive.;
          export BOOKIE_MEM="-Xmx128M";
          
          until timeout 15 bin/bookkeeper shell whatisinstanceid; do
            sleep 3;
          done;
        envFrom:
        - configMapRef:
            name: pulsar-mini-bookie
        volumeMounts:
        
      containers:
      - name: pulsar-mini-pulsar-init
        image: apachepulsar/pulsar-all:4.0.2
        imagePullPolicy: IfNotPresent
        command: ["timeout", "60", "sh", "-c"]
        args:
          - >-
            
            export PULSAR_MEM="-Xmx128M";
            bin/pulsar initialize-cluster-metadata \
              --cluster pulsar-mini \
              --zookeeper pulsar-mini-zookeeper:2181 \
              --configuration-store pulsar-mini-zookeeper:2181 \
              --web-service-url http://pulsar-mini-broker.pulsar.svc.cluster.local:8080/ \
              --web-service-url-tls https://pulsar-mini-broker.pulsar.svc.cluster.local:8443/ \
              --broker-service-url pulsar://pulsar-mini-broker.pulsar.svc.cluster.local:6650/ \
              --broker-service-url-tls pulsar+ssl://pulsar-mini-broker.pulsar.svc.cluster.local:6651/ ;
        volumeMounts:
          
      volumes:
        
      restartPolicy: OnFailure
---

