# Source: pulsar/templates/bookkeeper-pdb.yaml
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pulsar-mini-bookie"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: bookie
spec:
  selector:
    matchLabels:
      app: pulsar
      release: pulsar-mini
      component: bookie
  maxUnavailable: 1
---

# Source: pulsar/templates/broker-pdb.yaml
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pulsar-mini-broker"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: broker
spec:
  selector:
    matchLabels:
      app: pulsar
      release: pulsar-mini
      component: broker
  maxUnavailable: 1
---

# Source: pulsar/templates/proxy-pdb.yaml
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pulsar-mini-proxy"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: proxy
spec:
  selector:
    matchLabels:
      app: pulsar
      release: pulsar-mini
      component: proxy
  maxUnavailable: 1
---

# Source: pulsar/templates/zookeeper-pdb.yaml
#
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "pulsar-mini-zookeeper"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: zookeeper
spec:
  selector:
    matchLabels:
      app: pulsar
      release: pulsar-mini
      component: zookeeper
  maxUnavailable: 1
---
