# Source: pulsar/templates/bookkeeper-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-bookie"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: bookie
data:
  # common config
  
  zkServers: "pulsar-mini-zookeeper:2181"
  zkLedgersRootPath: "/ledgers"
  # enable bookkeeper http server
  httpServerEnabled: "true"
  httpServerPort: "8000"
  # config the stats provider
  statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
  # use hostname as the bookie id
  useHostNameAsBookieID: "true"
  # Do not retain journal files as it increase the disk utilization
  journalMaxBackups: "0"
  journalDirectories: "/pulsar/data/bookkeeper/journal"
  PULSAR_PREFIX_journalDirectories: "/pulsar/data/bookkeeper/journal"
  ledgerDirectories: "/pulsar/data/bookkeeper/ledgers"
  # TLS config
  
  PULSAR_GC: |
    -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem
  PULSAR_MEM: |
    -Xms128m -Xmx256m -XX:MaxDirectMemorySize=256m
  dbStorage_readAheadCacheMaxSizeMb: "32"
  dbStorage_rocksDB_blockCacheSize: "8388608"
  dbStorage_rocksDB_writeBufferSizeMB: "8"
  dbStorage_writeCacheMaxSizeMb: "32"
  diskCheckInterval: "1800"
  diskUsageLwmThreshold: "0.85"
  diskUsageThreshold: "0.95"
  diskUsageWarnThreshold: "0.9"
  gcWaitTime: "300000"
  isForceGCAllowWhenNoSpace: "true"
  majorCompactionInterval: "10800"
  majorCompactionThreshold: "0.8"
  minorCompactionInterval: "360"
  minorCompactionThreshold: "0.2"
---

# Source: pulsar/templates/broker-configmap.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-broker"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: broker
data:
  # Metadata settings
  zookeeperServers: "pulsar-mini-zookeeper:2181"
  configurationStoreServers: "pulsar-mini-zookeeper:2181"

  # Broker settings
  clusterName: pulsar-mini
  exposeTopicLevelMetricsInPrometheus: "true"
  numHttpServerThreads: "8"
  zooKeeperSessionTimeoutMillis: "30000"
  statusFilePath: "/pulsar/logs/status"

  # Tiered storage settings

  # Function Worker Settings
  # function worker configuration
  functionsWorkerEnabled: "false"

  # prometheus needs to access /metrics endpoint
  webServicePort: "8080"
  brokerServicePort: "6650"

  # Authentication Settings
  PULSAR_GC: |
    -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem
  PULSAR_MEM: |
    -Xms128m -Xmx256m -XX:MaxDirectMemorySize=256m
  autoSkipNonRecoverableData: "true"
  managedLedgerDefaultAckQuorum: "1"
  managedLedgerDefaultEnsembleSize: "1"
  managedLedgerDefaultWriteQuorum: "1"
---

# Source: pulsar/templates/proxy-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-proxy"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: proxy
data:
  clusterName: pulsar-mini
  statusFilePath: "/pulsar/logs/status"
  # prometheus needs to access /metrics endpoint
  webServicePort: "8080"
  servicePort: "6650"
  brokerServiceURL: pulsar://pulsar-mini-broker:6650
  brokerWebServiceURL: http://pulsar-mini-broker:8080

  # Authentication Settings
  PULSAR_GC: |
    -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.linkCapacity=1024 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem
  PULSAR_MEM: |
    -Xms64m -Xmx64m -XX:MaxDirectMemorySize=64m
  httpNumThreads: "8"
---

# Source: pulsar/templates/pulsar-manager-configmap.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-pulsar-manager"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: pulsar-manager
data:
  PULSAR_CLUSTER: pulsar-mini
  PULSAR_MANAGER_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
  DRIVER_CLASS_NAME: org.postgresql.Driver
  ENV_SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
  LOG_LEVEL: INFO
  PULSAR_MANAGER_OPTS: ' -Dlog4j2.formatMsgNoLookups=true'
  PULSAR_PEEK_MESSAGE: "true"
  REDIRECT_HOST: http://127.0.0.1
  REDIRECT_PORT: "9527"
  SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
  URL: jdbc:postgresql://127.0.0.1:5432/pulsar_manager
---

# Source: pulsar/templates/toolset-configmap.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-toolset"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: toolset
data:
  BOOKIE_LOG_APPENDER: "RollingFile"
  
  zkServers: "pulsar-mini-zookeeper:2181"
  zkLedgersRootPath: "/ledgers"
  # enable bookkeeper http server
  httpServerEnabled: "true"
  httpServerPort: "8000"
  # config the stats provider
  statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
  # use hostname as the bookie id
  useHostNameAsBookieID: "true"
  # talk to proxy
  webServiceUrl: "http://pulsar-mini-proxy:80/"
  brokerServiceUrl: "pulsar://pulsar-mini-proxy:6650/"
  # Authentication Settings 
  PULSAR_MEM: |
    -Xms64M -Xmx128M -XX:MaxDirectMemorySize=128M
---

# Source: pulsar/templates/zookeeper-configmap.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pulsar-mini-zookeeper"
  namespace: pulsar
  labels:
    app: pulsar
    chart: pulsar-3.9.0
    release: pulsar-mini
    heritage: Helm
    cluster: pulsar-mini
    component: zookeeper
data:
  dataDir: /pulsar/data/zookeeper
  PULSAR_PREFIX_serverCnxnFactory: org.apache.zookeeper.server.NIOServerCnxnFactory
  serverCnxnFactory: org.apache.zookeeper.server.NIOServerCnxnFactory
  PULSAR_GC: |
    -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -Dcom.sun.management.jmxremote -Djute.maxbuffer=10485760 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC -XX:+ExitOnOutOfMemoryError -XX:+PerfDisableSharedMem
  PULSAR_MEM: |
    -Xms64m -Xmx128m
---

